### ISSUE TITLE
Cannot add multiple POST routes in a resource

### ISSUE THREAD

**Issue by njd5475** [reprah/grape-route-helpers#14]
Looks like the options hash of grape routes does not contain the specific path name in it only the namespace.

``` ruby
resource :hamlet do
  post :tobe do
   "to be"
  end
  post :ornot do
    "or not"
  end
end

```

Submitted a PR #13

**Comment by reprah** [comment]
Hi, thanks for reporting this and taking the time to write a pull request!

I tried to reproduce this (a resource with multiple POST routes where only one route helper is created) but I couldn't. I made a [feature branch to show what I tried](https://github.com/reprah/grape-route-helpers/commit/2209e1bc8cbf004d3cd75f63081b40f399871e1e).

The code produces a helper function for both of the POST routes in the sample API I made. Am I misunderstanding the problem? What were you trying to do when you discovered it?

What version of grape-route-helpers and grape are you using, please?

**Comment by njd5475** [comment]
@reprah No problem love the gem, super useful.

It's only a problem with the `all_routes` method in 'lib/grape-route-helpers/all_routes.rb'.

``` ruby
    def all_routes
      routes = subclasses.flat_map { |s| s.send(:prepare_routes) }
      routes.uniq(&:options) # << this eliminates unique paths since the @options hash does not contain them
    end
```

Btw the specs do fail on the feature branch you created just not the one you added since that spec does not call the method above.

>  1) GrapeRouteHelpers::AllRoutes#all_routes when API is mounted within another API does not include the same route twice
>      Failure/Error: expect(all_route_options.size).to eq(7)
> 
> ```
>    expected: 7
>         got: 8
> 
>    (compared using ==)
>  # ./spec/grape_route_helpers/all_routes_spec.rb:23:in `block (4 levels) in <top (required)>'
> ```

**Comment by reprah** [comment]
@ njd5475 I get it now, thanks! I left a comment on your pull request.

**Comment by reprah** [comment]
@njd5475 This is fixed in the current master branch. Thank you for your bug report and PR, I really appreciate it.
