### ISSUE TITLE
Add support for custom route names

### ISSUE THREAD

**Issue by hedgesky** [reprah/grape-route-helpers#3]
Something similar to Rails' `as` option:

``` ruby
get :users, as: :members do
  ...
end
```

P.S. I guess you won [the competition](https://github.com/intridea/grape/pull/983#issuecomment-114283968) in spite of I published [my version](https://github.com/hedgesky/grape-named_routes) today, too :)

**Comment by reprah** [comment]
Good idea, I really liked this part of your implementation.

I'll take a closer look at your gem too. Are you interested in any collaboration?

**Comment by hedgesky** [comment]
Yes, I am. Our gems are rather different, so it would be difficult to reuse any part of my gem in your one, but I'll try to offer something when I have enough spare time.

**Comment by reprah** [comment]
I added custom routes to a new version I just pushed! Closing this ticket, thank you for making it.

**Comment by hedgesky** [comment]
:clap:
