### ISSUE TITLE
Version with dash causes SyntaxError

### ISSUE THREAD

**Issue by aderouineau** [reprah/grape-route-helpers#4]
When an API version contains a dash (`v1-draft`), it causes an issue at decorator creation:

```
syntax error, unexpected '-', expecting ';' or '\n'
        def infra_v1-draft_version_path(attributes = {})
                     ^
(eval):10: syntax error, unexpected keyword_end, expecting end-of-input
```

**Comment by reprah** [comment]
Hi, thanks for letting me know about this.

Since Ruby doesn't allow some characters in method names, what do you think should be done when someone has an API version that uses those characters (like a dash)? What would you expect the helper method to look like here?

**Comment by aderouineau** [comment]
I would say to replace any invalid character by an underscore. What do you think?

**Comment by reprah** [comment]
I agree!

**Comment by reprah** [comment]
Hi, this issue should be fixed in the latest version. Can you let me know if you run into further problems? Thanks!
